name: terraform-automation

on: [push]

concurrency:
    group: ${{ github.action == 'terraform-automation'}}


env:
    GCP_CREDS: "${{ secrets.GCP_SA_KEY }}"

defaults:
    run:
        working-directory: ./terraform

jobs:
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest

        steps:
            - name: checkout files
              uses: actions/checkout@v3

            - name: Store file as secret
              run: echo "$GCP_CREDS" >> creds.json
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Terraform init
              id: init
              run: terraform init
            
            - name: Terraform Plan
              id: plan
              run: terraform plan -input=false -no-color

            - name: Terraform Plan Status
              if: steps.plan.outcome == 'failure'
              run: exit 1
            
            - name: Terraform apply
              id: apply
              run: terraform apply -auto-approve -input=false -no-color

